name: Test

on: [push]

jobs:
  ruby:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Install gems
      run: |
        gem install bundler --no-doc
        bundle config path vendor/bundle
        bundle check || bundle install --jobs=4 --retry=3

    - name: Set up Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.19.x

    - name: Install npm dependencies
      run: |
        npm install

    - name: Run tests
      run: bundle exec rspec spec
